### ISSUE TITLE
ImportError: cannot import name _remove_dead_weakref

### ISSUE THREAD

**Issue by jarrettyeo** [jarrettyeo/blackbox#1]
On newer Mac OS versions, Blackbox may throw the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/usr/local/lib/python2.7/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
  File "blackbox.py", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/requests/__init__.py", line 43, in <module>
  File "/usr/local/lib/python2.7/site-packages/urllib3/__init__.py", line 8, in <module>
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 3, in <module>
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 26, in <module>
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14, in <module>
ImportError: cannot import name _remove_dead_weakref
```

Will be adding ```weakref``` as a new dependency in next release.

**Comment by jarrettyeo** [comment]
`backports.weakref` now added as a `package` in `setup.py`.

```
build_exe_options = {"packages": ['backports.weakref']}
```
